import unittest
from unittest.mock import MagicMock, patch

from webdav_for_filehold.document_service import DocumentService


class TestDocumentUpdate(unittest.TestCase):
    """
    Unit tests for updating documents via DocumentService.
    """

    def test_update_document_success(self) -> None:
        """
        Test successful document update.
        """
        # Setup
        session_id = "test_session"
        base_url = "http://test.com"
        new_name = "New Doc Name.pdf"

        # Mock Document Data
        mock_doc_data = MagicMock()
        del mock_doc_data.DocumentData
        mock_doc_data.CanEdit = True
        mock_doc_data.DocumentId = 100
        mock_doc_data.DocumentSchemaId = 1
        mock_doc_data.MetadataVersionId = 500
        mock_doc_data.VersionNumber = "1.0"
        mock_doc_data.Name = "Old Name"
        mock_doc_data.Extension = ".pdf"

        # Mocks for Clients
        mock_schema_client = MagicMock()
        mock_finder_client = MagicMock()
        mock_manager_client = MagicMock()

        # Mock Schema Responses
        mock_schema = MagicMock()
        mock_schema.VersionControlFieldId = 10
        mock_schema_client.service.GetDocumentSchema.return_value = mock_schema

        mock_vc_field = MagicMock()
        mock_vc_field.IsAutoGenerated = True  # Must be true for success
        mock_schema_client.service.GetVersionControlField.return_value = mock_vc_field

        # Mock Finder Response (GetDocumentDetails)
        mock_details = MagicMock()

        # Columns
        col1 = MagicMock()
        col1.IsSystem = False
        col1.ColumnIndex = 0
        col1.MetadataFieldId = 1001

        col2 = MagicMock()
        col2.IsSystem = True  # Should be skipped
        col2.ColumnIndex = 1

        col3 = MagicMock()
        col3.IsSystem = False
        col3.ColumnIndex = 2
        col3.MetadataFieldId = 1002
        col3.Type = 'Text'

        col4 = MagicMock()
        col4.IsSystem = False
        col4.ColumnIndex = 3
        col4.MetadataFieldId = 1003
        col4.Type = 'DropdownMenu'

        mock_details.Columns.FieldDefinition = [col1, col2, col3, col4]

        # Values
        dd_choice1 = MagicMock()
        dd_choice1.Id = 55
        dd_choice1.Value = "Choice 1"

        dd_choice2 = MagicMock()
        dd_choice2.Id = 56
        dd_choice2.Value = "Choice 2"

        mock_values = MagicMock()
        mock_values.DataColumns.anyType = ["Value1", "SystemVal", "Value2", [dd_choice1, dd_choice2]]
        mock_details.DocumentValues.DocumentData = [mock_values]

        mock_finder_client.service.GetDocumentDetails.return_value = mock_details

        # Mock Manager Response (SetMetadata)
        mock_manager_client.service.SetMetadata.return_value = 501  # New MetadataVersionId

        # Configure type_factory to return a pass-through for ArrayOfInt
        mock_factory = MagicMock()
        mock_type = MagicMock(side_effect=lambda x: x)  # When ArrayOfInt(val) is called, return val
        mock_factory.ArrayOfInt = mock_type
        mock_manager_client.type_factory.return_value = mock_factory

        with patch('webdav_for_filehold.client_factory.ClientFactory.get_document_schema_manager_client', return_value=mock_schema_client), \
             patch('webdav_for_filehold.client_factory.ClientFactory.get_document_finder_client', return_value=mock_finder_client), \
             patch('webdav_for_filehold.client_factory.ClientFactory.get_document_manager_client', return_value=mock_manager_client):

            result = DocumentService.update_document(session_id, base_url, mock_doc_data, new_name)

            self.assertEqual(result, 501)

            # Verify Schema Checks
            mock_schema_client.service.GetDocumentSchema.assert_called_with(1)
            mock_schema_client.service.GetVersionControlField.assert_called_with(10)

            # Verify Get Details
            mock_finder_client.service.GetDocumentDetails.assert_called_with(metadataVersionId=500)

            # Verify Set Metadata
            # Check args
            _, kwargs = mock_manager_client.service.SetMetadata.call_args
            self.assertEqual(kwargs['prevMetadataVersionId'], 500)
            self.assertEqual(kwargs['documentSchemaId'], 1)
            self.assertEqual(kwargs['documentName'], "New Doc Name")  # Ext stripped
            self.assertEqual(kwargs['overwritePrevious'], False)

            fields_arg = kwargs['fieldsWithValues']
            self.assertIn('FieldWithValue', fields_arg)
            fwv = fields_arg['FieldWithValue']
            self.assertEqual(len(fwv), 3)
            self.assertEqual(fwv[0]['FieldId'], 1001)
            self.assertEqual(fwv[0]['FieldValue'].value, "Value1")
            self.assertEqual(fwv[1]['FieldId'], 1002)
            self.assertEqual(fwv[1]['FieldValue'].value, "Value2")
            self.assertEqual(fwv[2]['FieldId'], 1003)
            self.assertEqual(fwv[2]['FieldValue'].value, [55, 56])

    def test_update_document_permission_denied(self) -> None:
        """
        Test that updating a document fails if the user doesn't have edit permissions.
        """
        mock_doc_data = MagicMock()
        del mock_doc_data.DocumentData
        mock_doc_data.CanEdit = False

        with patch('webdav_for_filehold.client_factory.ClientFactory.get_document_manager_client'), \
             patch('webdav_for_filehold.client_factory.ClientFactory.get_document_finder_client'), \
             patch('webdav_for_filehold.client_factory.ClientFactory.get_document_schema_manager_client'):
            with self.assertRaises(Exception) as cm:
                DocumentService.update_document("sess", "url", mock_doc_data, "name")
            self.assertIn("cannot edit document", str(cm.exception))

    def test_update_document_bad_vc_field(self) -> None:
        """
        Test that updating a document fails if the version control field is not auto-generated.
        """
        # Setup
        mock_doc_data = MagicMock()
        mock_doc_data.CanEdit = True
        mock_doc_data.VersionNumber = "1.0"

        mock_schema_client = MagicMock()
        mock_schema = MagicMock()
        mock_schema.VersionControlFieldId = 10
        mock_schema_client.service.GetDocumentSchema.return_value = mock_schema

        mock_vc_field = MagicMock()
        mock_vc_field.IsAutoGenerated = False  # FAIL
        mock_schema_client.service.GetVersionControlField.return_value = mock_vc_field

        with patch('webdav_for_filehold.client_factory.ClientFactory.get_document_schema_manager_client', return_value=mock_schema_client):
            with self.assertRaises(Exception) as cm:
                DocumentService.update_document("sess", "url", mock_doc_data, "name")
            self.assertIn("not auto-generated", str(cm.exception))


if __name__ == '__main__':
    unittest.main()
